name: thesis_mobile_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  dots_indicator: ^2.1.0
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  modal_bottom_sheet: ^3.0.0-pre
  equatable: ^2.0.5
  dio: ^5.0.1
  flutter_pretty_dio_logger: ^3.0.0
  flutter_bloc: ^8.1.2
  no_context_navigation: ^2.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  validators: ^3.0.0
  flutter_progress_hud: ^2.0.2
  bloc_concurrency: ^0.2.1
  intl: ^0.18.0
  shimmer: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  adaptive_theme: ^3.2.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/introduction/
    - assets/images/icons/

  fonts:
    - family: 'SFProDisplay'
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-UltralightItalic.otf
          style: italic
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-ThinItalic.otf
          style: italic
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-HeavyItalic.otf
          style: italic
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-BlackItalic.otf
          style: italic
          weight: 900
