name: thesis_mobile_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  dots_indicator: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/images/
    - lib/assets/images/introduction/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: lib/assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: lib/assets/fonts/SF-Pro-Display-UltralightItalic.otf
          style: italic
          weight: 100
        - asset: lib/assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: lib/assets/fonts/SF-Pro-Display-ThinItalic.otf
          style: italic
          weight: 200
        - asset: lib/assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: lib/assets/fonts/SF-Pro-Display-LightItalic.otf
          style: italic
          weight: 300
        - asset: lib/assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/SF-Pro-Display-RegularItalic.otf
          style: italic
          weight: 400
        - asset: lib/assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/SF-Pro-Display-MediumItalic.otf
          style: italic
          weight: 500
        - asset: lib/assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: lib/assets/fonts/SF-Pro-Display-SemiboldItalic.otf
          style: italic
          weight: 600
        - asset: lib/assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/SF-Pro-Display-BoldItalic.otf
          style: italic
          weight: 700
        - asset: lib/assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: lib/assets/fonts/SF-Pro-Display-HeavyItalic.otf
          style: italic
          weight: 800
        - asset: lib/assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: lib/assets/fonts/SF-Pro-Display-BlackItalic.otf
          style: italic
          weight: 900
