// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbV7ylaz5RNHZlrq62Y6Fk_VA1Tbggqy4',
    appId: '1:1017556609378:android:781780fd4961a7f60f243b',
    messagingSenderId: '1017556609378',
    projectId: 'sk-progress-pushes',
    databaseURL: 'https://sk-progress-pushes.firebaseio.com',
    storageBucket: 'sk-progress-pushes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSLa5WeR3xxw6QCYP4Nh76vJZiLjCLkL8',
    appId: '1:1017556609378:ios:84d31fdced854aa10f243b',
    messagingSenderId: '1017556609378',
    projectId: 'sk-progress-pushes',
    databaseURL: 'https://sk-progress-pushes.firebaseio.com',
    storageBucket: 'sk-progress-pushes.appspot.com',
    androidClientId:
        '1017556609378-0gesjtauuts81f8qs2rvmam416d4l6qm.apps.googleusercontent.com',
    iosClientId:
        '1017556609378-0dl5a6k1kjh98etjksv6vpp5qqgk2jdm.apps.googleusercontent.com',
    iosBundleId: 'team.progress.scprogress',
  );
}
