name: android_ci

on:
  pull_request:
    branches: dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: flutter pub get
      #- run: flutter build apk
      - run: flutter build appbundle
