name: android_ci

on:
  pull_request:
    branches: dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '20.0.2'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
